In [58]:
from sklearn import preprocessing
import pandas as pd
import numpy as np

In [59]:
df = pd.read_csv("D:/Datasets/base_datos_2008.csv", nrows=1e5)
df = df[["ArrDelay","DepDelay","Distance","AirTime"]].dropna()

In [60]:
# Metodo de estandarizacion X_scaled
X_scaled = preprocessing.scale(df)
# Obtenemos un array con valores cercamos al cero
X_scaled


array([[-0.63713243, -0.08247884,  0.40657043,  0.4452521 ],
       [-0.12045009,  0.3068154 ,  0.40657043,  0.38990966],
       [ 0.26706167, -0.08247884, -0.26709367, -0.29264705],
       ...,
       [ 1.84940134,  2.18250582,  0.53445243,  0.31611975],
       [ 0.17018373,  0.37759617,  0.53445243,  0.1869874 ],
       [ 0.17018373, -0.25943077,  0.53445243,  0.22388235]])

In [61]:
# calculamos lam media para cada columna axis = 0 columnas axis = 1 filas
X_scaled.mean(axis=0)

array([2.47651119e-17, 1.07267490e-17, 1.19506063e-16, 1.01364179e-16])

In [62]:
# calculamos la desviasión estandar para cada columna
# Convertimos todas nuestras variables a una misma escala.
X_scaled.std(axis=0)


array([1., 1., 1., 1.])

In [63]:
df.iloc[2]

ArrDelay     14.0
DepDelay      8.0
Distance    515.0
AirTime      76.0
Name: 2, dtype: float64

In [64]:
X_scaled[2]

array([ 0.26706167, -0.08247884, -0.26709367, -0.29264705])

In [65]:
X_scaled[2]

array([ 0.26706167, -0.08247884, -0.26709367, -0.29264705])

In [67]:
min_max_scaler = preprocessing.MinMaxScaler(feature_range=(0,10))
X_train_minmax = min_max_scaler.fit_transform(df)
X_train_minmax

array([[0.77199282, 0.92857143, 3.15557514, 2.91316527],
       [1.05924596, 1.125     , 3.15557514, 2.82913165],
       [1.27468582, 0.92857143, 1.85544293, 1.79271709],
       ...,
       [2.15439856, 2.07142857, 3.4023799 , 2.71708683],
       [1.22082585, 1.16071429, 3.4023799 , 2.5210084 ],
       [1.22082585, 0.83928571, 3.4023799 , 2.57703081]])

## Transformación de variables  categorias a Dummies

In [69]:
df = pd.read_csv("D:/Datasets/base_datos_2008.csv", nrows=100)
pd.get_dummies(df["Origin"]).astype(int)

IAD  IND  ISP  JAN  JAX  LAS
0     1    0    0    0    0    0
1     1    0    0    0    0    0
2     0    1    0    0    0    0
3     0    1    0    0    0    0
4     0    1    0    0    0    0
..  ...  ...  ...  ...  ...  ...
95    0    0    0    0    0    1
96    0    0    0    0    0    1
97    0    0    0    0    0    1
98    0    0    0    0    0    1
99    0    0    0    0    0    1

[100 rows x 6 columns]